	DROP DATABASE if EXISTS JAVADATA_MOHAMMED;
	CREATE DATABASE JAVADATA_MOHAMMED;
	
	CREATE TABLE employ(
		id INT(15) PRIMARY KEY AUTO_INCREMENT,
		name VARCHAR(30),
		gender BOOLEAN,
		birth_date DATE,
		salary REAL
	);